import { canonical, clone, id } from '../core/util.js';
import { DOMAIN_DEFAULTS, KIND_LABELS, domainView } from '../core/domain.js';
import { p1Defaults } from '../core/p1-config.js';
import { summaryGraph } from '../core/composer.js';
import { parseStoryTime } from '../core/story-time.js';

const el = (tag,text,className) => { const node = document.createElement(tag); if (text !== undefined) node.textContent = text; if (className) node.className = className; return node; };
const labels = { identity:'身份', hostCharacterKey:'酒馆角色身份键', profile:'固定档案', appearance:'外貌', personality:'性格', experiences:'经历', current:'当前状态', clothing:'衣着', body:'身体状况', emotion:'情绪', presence:'在场状态', locationId:'地点 ID', rank:'角色等级', starred:'星标', pinned:'置顶', affection:'数值好感（未知填 null）', innerAttitude:'内心态度', outerAttitude:'外在态度', lifeDetails:'生活档案', preferences:'偏好', habits:'习惯（text 与 observations）', recent:'近况', birth:'出生时间锚点', description:'描述', quantity:'数量', unit:'单位', ownerId:'持有人 ID', storage:'存放方式', importance:'重要程度', status:'状态', parentId:'父地点 ID', fixedFeatures:'固定特征', focus:'本轮场景焦点', fromId:'关系起点 ID', toId:'关系对象 ID', relation:'关系', basis:'认知/关系依据', visibility:'可见范围', audienceIds:'知情角色 ID（逗号分隔）', text:'内容', factId:'事实 ID', actorId:'角色 ID', awareness:'认知状态', sourceActorId:'传播来源角色 ID', storyTime:'故事时间', type:'事项类型', deadline:'期限', actorIds:'相关角色 ID（逗号分隔）', time:'当前故事时间', history:'时间推进记录' };
const choices = { identity:['protagonist','npc'], presence:['present','nearby','absent','following','unknown'], rank:['core','major','minor'], innerAttitude:['unknown','hostile','cold','neutral','friendly','devoted'], outerAttitude:['unknown','hostile','cold','neutral','friendly','devoted'], storage:['carried','stored','unknown'], importance:['normal','important','critical'], visibility:['public','private','narrator'], awareness:['experienced','heard','suspected','unknown'], type:['promise','task','foreshadow','mystery'] };
const valueLabels = {protagonist:'主角',npc:'NPC',present:'在场',nearby:'附近',absent:'离场',following:'随行',unknown:'未知',core:'核心',major:'主要',minor:'次要',hostile:'敌对',cold:'冷淡',neutral:'中性',friendly:'友善',devoted:'亲密',carried:'随身',stored:'寄存',normal:'普通',important:'重要',critical:'关键',public:'公开',private:'指定知情角色',narrator:'仅保存，不注入',experienced:'亲历',heard:'听说',suspected:'怀疑',promise:'约定',task:'任务',foreshadow:'伏笔',mystery:'悬念',open:'未结',completed:'完成',cancelled:'取消',expired:'失效',active:'有效',consumed:'已消耗',deleted:'已删除',light:'轻量',advanced:'进阶',full:'完整'};
function download(name,value) { const url = URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})); const link = el('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url),1000); }
function inputField(parent,label,value = '',type = 'text') { const wrapper = el('label',label,'memory-core-field'); const input = el(type === 'textarea' ? 'textarea' : 'input'); if (type !== 'textarea') input.type = type; input.value = value; wrapper.append(input); parent.append(wrapper); return input; }
function selectField(parent,label,options,value) { const wrapper = el('label',label,'memory-core-field'); const input = el('select'); input.setAttribute('aria-label',label); for (const item of options) { const option = el('option',Array.isArray(item) ? item[1] : valueLabels[item] ?? item); option.value = Array.isArray(item) ? item[0] : item; input.append(option); } if (value !== undefined) input.value = value; wrapper.append(input); parent.append(wrapper); return input; }
function checkField(parent,label,value = false) { const wrapper = el('label',undefined,'memory-core-check-label'); const input = el('input'); input.type = 'checkbox'; input.checked = value; wrapper.append(input,el('span',label)); parent.append(wrapper); return input; }
function section(parent,title,description) { const node = el('section',undefined,'memory-core-card memory-core-workbench-section'); node.append(el('h3',title)); if (description) node.append(el('p',description,'memory-core-muted')); parent.append(node); return node; }
function fieldEditor(parent,key,value,kind) {
  const label = labels[key] ?? key;
  if (value && typeof value === 'object' && !Array.isArray(value) && ['profile','current','lifeDetails'].includes(key)) { const group = el('fieldset'); group.append(el('legend',label)); parent.append(group); const getters = Object.entries(value).map(([k,v]) => [k,fieldEditor(group,k,v,kind)]); return () => Object.fromEntries(getters.map(([k,get]) => [k,get()])); }
  if (key === 'affection') { const input = inputField(parent,label,value ?? 'null'); return () => !input.value.trim() || input.value.trim() === 'null' ? null : Number(input.value); }
  if (['ownerId','locationId','parentId','sourceActorId'].includes(key)) { const input = inputField(parent,`${label}（未知留空）`,value ?? ''); return () => input.value.trim() && input.value.trim() !== 'null' ? input.value.trim() : null; }
  if (typeof value === 'boolean') { const input = checkField(parent,label,value); return () => input.checked; }
  if (choices[key]) { const input = selectField(parent,label,choices[key],value ?? 'unknown'); return () => input.value === 'unknown' && ['innerAttitude','outerAttitude'].includes(key) ? null : input.value; }
  if (key === 'status') { const input = selectField(parent,label,kind === 'thread' ? ['open','completed','cancelled','expired'] : ['active','consumed','deleted'],value); return () => input.value; }
  if (['audienceIds','actorIds'].includes(key)) { const input = inputField(parent,label,(value ?? []).join(',')); return () => input.value.split(',').map(x => x.trim()).filter(Boolean); }
  if (typeof value === 'number') { const input = inputField(parent,label,value,'number'); return () => Number(input.value); }
  if (value === null || typeof value === 'object') { const input = inputField(parent,`${label} · JSON`,JSON.stringify(value,null,2),'textarea'); return () => JSON.parse(input.value); }
  const input = inputField(parent,label,value,typeof value === 'string' && (value.length > 80 || ['text','description','fixedFeatures','focus','experiences'].includes(key)) ? 'textarea' : 'text'); return () => input.value;
}
export function mountWorkbench(container,runtime,feedback) {
  let feedbackSequence = 0; const report = feedback; feedback = (...args) => { feedbackSequence++; report(...args); };
  const nav = el('div',undefined,'memory-core-actions'); container.append(nav); const pages = {}; let activePage = 'memory';
  const pageNames = { memory:'分析与审阅', state:'人物与状态', prompt:'生成材料', world:'世界书', api:'任务渠道', migration:'旧总结导入', settings:'选项与提示词' };
  const select = key => { activePage = key; for (const [name,page] of Object.entries(pages)) page.hidden = name !== key; };
  const action = (parent,label,handler) => { const button = el('button',label,'menu_button memory-core-button'); button.type = 'button'; let group = parent.classList.contains('memory-core-actions') ? parent : parent.lastElementChild?.classList.contains('memory-core-actions') ? parent.lastElementChild : null; if (!group) {group = el('div',undefined,'memory-core-actions'); parent.append(group);} group.append(button); button.addEventListener('click',async () => { button.disabled = true; const prior = feedbackSequence; try { await handler(); if (prior === feedbackSequence) feedback('操作已完成'); } catch (error) { runtime.logger.error(error); feedback(`${error.code ?? 'ERROR'}：${error.message}`,true); } finally { button.disabled = false; render(true); } }); return button; };
  for (const [key,name] of Object.entries(pageNames)) { const page = el('div',undefined,'memory-core-workbench-page'); pages[key] = page; container.append(page); action(nav,name,() => select(key)); }
  select('memory');
  const intro = section(pages.memory,'从正文建立可追溯的记忆','先启用故事记忆并配置 API，再扫描范围、审阅结果。生成材料页可查看下一次正文生成会提交的内容。');
  const guide = el('p'); intro.append(guide); const quickMode = selectField(intro,'界面模式',['light','advanced','full'],runtime.settings.snapshot().ui.mode); quickMode.addEventListener('change',() => void runtime.settings.update({ui:{...runtime.settings.snapshot().ui,mode:quickMode.value}}).catch(error => feedback(error.message,true))); const draftEdits = new Map();
  const rangeCard = section(pages.memory,'范围分析','中断后再次扫描相同范围，只处理未覆盖或尚未提取状态的楼层。');
  const rangeGrid = el('div',undefined,'memory-core-workbench-grid'); rangeCard.append(rangeGrid);
  const start = inputField(rangeGrid,'起始楼层',1,'number'); start.min = '1'; const end = inputField(rangeGrid,'结束楼层',9999,'number'); const limit = inputField(rangeGrid,'本次最多楼数',20,'number');
  const review = checkField(rangeCard,'结果先审阅',true); const missing = checkField(rangeCard,'只扫描缺口',true);
  action(rangeCard,'分析选定范围',() => runtime.p1.range({start:Number(start.value),end:Number(end.value),limit:Number(limit.value),review:review.checked,missingOnly:missing.checked}));
  action(rangeCard,'停止批量任务',() => runtime.p1.stop());
  action(rangeCard,'排除这个范围',() => runtime.p1.setExcluded(runtime.getSnapshot().messages.filter(m => m.index + 1 >= Number(start.value) && m.index + 1 <= Number(end.value)).map(m => m.id),true));
  action(rangeCard,'恢复这个范围',() => runtime.p1.setExcluded(runtime.getSnapshot().messages.filter(m => m.index + 1 >= Number(start.value) && m.index + 1 <= Number(end.value)).map(m => m.id),false));
  action(rangeCard,'隐藏已覆盖旧楼',() => runtime.p1.hideCovered()); action(rangeCard,'恢复本插件隐藏的楼层',() => runtime.p1.hideCovered(true));
  const progress = el('p'); progress.setAttribute('role','status'); rangeCard.append(progress);
  const draftsCard = section(pages.memory,'待审阅结果','正文或相关状态变化后会拒绝旧结果。后续楼层依赖前序分析；确认后续结果会按顺序提交其前序结果，请先审阅整批。'); const draftsList = el('div',undefined,'memory-core-summary-list'); draftsCard.append(draftsList);
  const nodesCard = section(pages.memory,'摘要树与原始事件','选择互不重叠的摘要节点生成压缩预览。撤销压缩后会重新使用子摘要。'); const rawMode = checkField(nodesCard,'同时显示当前原始正文',false); rawMode.addEventListener('change',() => render(true)); const nodeSelections = new Set();
  action(nodesCard,'预览合并压缩',() => runtime.p1.compress([...nodeSelections])); const nodeList = el('div',undefined,'memory-core-summary-list'); nodesCard.append(nodeList);

  const stateCard = section(pages.state,'人物、物品、地图与时间线','显示和注入使用同一档案版本。人物关系有方向，认知引用事实 ID。数量、单位和存放方式分别维护。');
  const filters = el('div',undefined,'memory-core-workbench-grid'); stateCard.append(filters);
  const kindFilter = selectField(filters,'类型',[['','全部'],...Object.entries(KIND_LABELS)]); const search = inputField(filters,'名称搜索'); const levelFilter = selectField(filters,'筛选',['全部','core','major','minor','normal','important','critical','present','nearby','absent','following','星标','置顶']);
  for (const input of [kindFilter,search,levelFilter]) input.addEventListener('input',() => render(true));
  const selectedEntities = new Set(); action(stateCard,'删除所选记录',async () => {await runtime.p1.removeEntities([...selectedEntities]); selectedEntities.clear();});
  action(stateCard,'所选时间线标为关键',() => runtime.p1.manual([...selectedEntities].filter(entityId => runtime.getSnapshot().state.entities[entityId]?.kind === 'timeline').map(entityId => ({type:'set',entityId,path:['importance'],value:'critical'})),'事件分级'));
  const stateList = el('div',undefined,'memory-core-summary-list'); stateCard.append(stateList);
  const clockCard = section(pages.state,'故事时间与位置','公历和自定义历法分别解析；未知保留未知，倒叙时间单独记录。出生锚点完整时才计算年龄。'); const timeText = inputField(clockCard,'日期、相对时间或时间标签'); const locationId = inputField(clockCard,'当前地点 ID（未知留空）');
  action(clockCard,'人工纠正当前故事',async () => { const config = runtime.settings.snapshot(); const current = runtime.getSnapshot().state.entities.story_clock?.fields ?? DOMAIN_DEFAULTS.clock; const time = parseStoryTime(timeText.value,current.time,config.story.calendar); await runtime.p1.saveEntity({id:'story_clock',kind:'clock',name:'当前故事',fields:{...current,time,locationId:locationId.value.trim() || null,history:[...current.history,{time,origin:'human'}]}},{lock:true}); });
  const mapList = el('div',undefined,'memory-core-map-tree'); clockCard.append(mapList);
  const editorCard = section(pages.state,'创建或编辑记录','别名不会把同名对象自动合并。人工字段锁可阻止后续模型改写，解锁按钮会保留数据。');
  const editKind = selectField(editorCard,'记录类型',Object.entries(KIND_LABELS),'character'); const editId = inputField(editorCard,'记录 ID（新建留空）'); const editName = inputField(editorCard,'名称'); const editAliases = inputField(editorCard,'别名（逗号分隔）'); const lock = checkField(editorCard,'锁定本次人工字段',true); const editFields = el('div',undefined,'memory-core-workbench-grid'); editorCard.append(editFields); let getters = [];
  function loadEditor(entity = null) { const kind = entity?.kind ?? editKind.value; editKind.value = kind; editId.value = entity?.id ?? ''; editName.value = entity?.name ?? ''; editAliases.value = entity?.aliases.join(',') ?? ''; editFields.replaceChildren(); getters = Object.entries(entity?.fields ?? DOMAIN_DEFAULTS[kind]).filter(([key]) => key !== 'sourceMessageIds').map(([key,value]) => [key,fieldEditor(editFields,key,value,kind)]); }
  editKind.addEventListener('change',() => loadEditor()); loadEditor();
  action(editorCard,'保存记录',() => runtime.p1.saveEntity({id:editId.value.trim() || undefined,kind:editKind.value,name:editName.value.trim(),aliases:editAliases.value.split(',').map(x => x.trim()).filter(Boolean),fields:Object.fromEntries(getters.map(([key,get]) => [key,get()]))},{lock:lock.checked}));
  action(editorCard,'新建另一条',() => loadEditor());
  action(editorCard,'解除这个记录的字段锁',() => runtime.p1.manual(Object.values(runtime.getSnapshot().state.locks).filter(l => l.entityId === editId.value).map(l => ({type:'unlock',entityId:l.entityId,path:l.path})),'解锁记录'));
  const undoCard = section(pages.state,'人工操作撤销','只有目标仍与操作完成时一致，才能撤销，避免覆盖后续修订。'); const undoList = el('div'); undoCard.append(undoList);

  const promptCard = section(pages.prompt,'统一生成材料','摘要、状态和时间线只在这里组装。无法确定当前角色时，只发送明确公开的信息。token 数默认是估计；宿主计数可另行核查。');
  const actors = inputField(promptCard,'本次知情角色 ID（逗号分隔；留空按酒馆当前角色识别）',runtime.settings.snapshot().prompt.actorIds.join(','));
  action(promptCard,'保存角色范围',() => runtime.settings.update({prompt:{...runtime.settings.snapshot().prompt,actorIds:actors.value.split(',').map(x => x.trim()).filter(Boolean)}}));
  const promptSwitches = el('div',undefined,'memory-core-workbench-grid'); promptCard.append(promptSwitches);
  const sectionLabels = {summaries:'摘要',characters:'人物',items:'物品',scenes:'场景',relations:'关系',knowledge:'认知',timeline:'时间线',threads:'约定与悬念',rpg:'RPG（后续阶段）',settings:'设定材料'};
  const promptSectionInputs = {}; for (const [key,value] of Object.entries(runtime.settings.snapshot().prompt.sections)) { const input = checkField(promptSwitches,`发送 ${sectionLabels[key]}`,value); promptSectionInputs[key] = input; input.addEventListener('change',() => { const config = runtime.settings.snapshot(); void runtime.settings.update({prompt:{...config.prompt,sections:{...config.prompt.sections,[key]:input.checked}}}).catch(error => feedback(error.message,true)); }); }
  action(promptCard,'更新注入预览',async () => { await runtime.sync(); await runtime.p1.readMaterials(); await runtime.p1.refreshPrompt(); });
  action(promptCard,'使用宿主计算 token',async () => { const bundle = runtime.p1.previewPrompt(); const context = runtime.host.context(); if (typeof context.getTokenCountAsync !== 'function') throw new Error('宿主没有 token 计数接口'); const count = await context.getTokenCountAsync(bundle.text); feedback(`宿主计数 ${count} token；本插件估计 ${bundle.tokenCount}`); });
  const promptInfo = el('p'); const promptOutput = el('pre',undefined,'memory-core-log-output'); promptCard.append(promptInfo,promptOutput);
  const submittedDetails = el('details'); const submittedOutput = el('pre',undefined,'memory-core-log-output'); submittedDetails.append(el('summary','最近一次提交给宿主的实际材料与来源'),submittedOutput); promptCard.append(submittedDetails);

  const worldCard = section(pages.world,'外部设定材料','角色卡、用户设定和世界书作为设定层读取。基础扫描支持常驻与关键词，需高级递归/向量/概率的条目会显示跳过原因。');
  const worldEnabled = checkField(worldCard,'启用世界书读取',runtime.settings.snapshot().worldbook.enabled); const bound = checkField(worldCard,'读取角色绑定与聊天绑定的世界书',runtime.settings.snapshot().worldbook.bound); const booksInput = inputField(worldCard,'手选世界书名称（逗号分隔）',runtime.settings.snapshot().worldbook.books.join(','));
  const scanDepth = inputField(worldCard,'关键词扫描近期楼数',runtime.settings.snapshot().worldbook.scanDepth,'number');
  action(worldCard,'保存并读取世界书',async () => { const config = runtime.settings.snapshot(); await runtime.settings.update({worldbook:{...config.worldbook,enabled:worldEnabled.checked,bound:bound.checked,books:booksInput.value.split(',').map(x => x.trim()).filter(Boolean),scanDepth:Number(scanDepth.value)}}); await runtime.p1.readMaterials(); });
  const worldList = el('div',undefined,'memory-core-summary-list'); worldCard.append(worldList);

  const apiCard = section(pages.api,'按任务选择渠道','摘要、提取和压缩分别路由；规划与 Agent 的渠道可以提前保存，模块启用后才会运行。'); const routes = {};
  for (const task of ['summary','extraction','compression','planning','agent']) routes[task] = selectField(apiCard,task,[]);
  action(apiCard,'保存任务路由',() => runtime.settings.update({routing:{...runtime.settings.snapshot().routing,...Object.fromEntries(Object.entries(routes).map(([task,input]) => [task,input.value]))}}));
  const fallback = checkField(apiCard,'独立渠道网络失败后允许回退主 API',runtime.settings.snapshot().api.fallbackToMain); fallback.addEventListener('change',() => void runtime.settings.update({api:{fallbackToMain:fallback.checked}}).catch(error => feedback(error.message,true)));
  const channelSelect = selectField(apiCard,'编辑独立渠道',[]); const apiForm = el('div',undefined,'memory-core-workbench-grid'); apiCard.append(apiForm);
  const model = inputField(apiForm,'模型名称'); const temperature = inputField(apiForm,'温度',.7,'number'); const outputLimit = inputField(apiForm,'渠道最大输出 token',2048,'number'); const stream = checkField(apiForm,'启用流式返回',false); const omit = inputField(apiForm,'排除不支持的参数（temperature,max_tokens,stream）');
  function loadChannel() { const channel = runtime.settings.snapshot().channels.find(c => c.id === channelSelect.value); if (channel) { model.value = channel.model; temperature.value = channel.temperature ?? .7; outputLimit.value = channel.maxTokens ?? 2048; stream.checked = channel.stream ?? false; omit.value = (channel.omitParameters ?? []).join(','); } }
  channelSelect.addEventListener('change',loadChannel);
  action(apiCard,'保存模型与参数',() => { const config = runtime.settings.snapshot(); return runtime.settings.update({channels:config.channels.map(c => c.id === channelSelect.value ? {...c,model:model.value.trim(),temperature:Number(temperature.value),maxTokens:Number(outputLimit.value),stream:stream.checked,omitParameters:omit.value.split(',').map(x => x.trim()).filter(Boolean)} : c)}); });
  action(apiCard,'健康检查所选渠道',async () => feedback(`渠道响应：${await runtime.testChannel(channelSelect.value || 'main')}`)); const capabilities = el('pre',undefined,'memory-core-log-output'); apiCard.append(capabilities);

  const migrationCard = section(pages.migration,'导入旧总结与最终状态','支持手写总结或本插件 P1 JSON。预览会列出冲突、未知字段与历史缺口；原始输入保留，可撤销。完整旧插件格式迁移属于 P5。'); const migrationText = inputField(migrationCard,'旧总结正文或 JSON','', 'textarea'); const migrationStart = inputField(migrationCard,'覆盖起始楼层',1,'number'); const migrationEnd = inputField(migrationCard,'覆盖结束楼层',1,'number'); const migrationConflict = selectField(migrationCard,'同 ID 冲突策略',[['ask','先查看冲突'],['keep','保留当前'],['replace','使用导入字段']]); const migrationVisibility = selectField(migrationCard,'总结可见范围',['narrator','public','private']); const migrationActors = inputField(migrationCard,'私密总结知情角色 ID（逗号分隔）'); let migrationPreview = null; const migrationReport = el('pre',undefined,'memory-core-log-output'); migrationCard.append(migrationReport);
  action(migrationCard,'预览迁移',() => { let raw; try { raw = JSON.parse(migrationText.value); } catch { raw = migrationText.value; } if (typeof raw === 'string') raw = {summary:raw}; raw.visibility = migrationVisibility.value; raw.audienceIds = migrationActors.value.split(',').map(x => x.trim()).filter(Boolean); migrationPreview = runtime.p1.migrationPreview(raw,{start:Number(migrationStart.value),end:Number(migrationEnd.value),conflict:migrationConflict.value}); migrationReport.textContent = JSON.stringify({conflicts:migrationPreview.conflicts,unknownFields:migrationPreview.unknownFields,uncoveredCount:migrationPreview.uncoveredCount,warning:migrationPreview.warning},null,2); });
  action(migrationCard,'提交这个迁移预览',() => { if (!migrationPreview) throw new Error('请先预览迁移'); return runtime.p1.migrate(migrationPreview); });
  action(migrationCard,'导出保留的原始输入',() => { if (!migrationPreview) throw new Error('请先预览'); download('memory-migration-original.json',migrationPreview.input); });

  const optionsCard = section(pages.settings,'记忆选项','触发阈值、近期窗口和批次限制分别设置。纯摘要模式会停止人物等结构化提取。'); const memoryInputs = {};
  const memoryLabels = {autoSummarize:'自动分析正文',summaryOnly:'只生成摘要',requireReview:'分析结果先审阅',hideCovered:'提交成功后隐藏已覆盖旧楼',autoCompress:'达到阈值自动压缩',maxTokens:'任务输出 token 上限',maxMessagesPerRun:'每批楼数上限',floorThreshold:'自动触发楼数阈值',tokenThreshold:'自动触发 token 估计阈值（0 关闭）',keepRecent:'隐藏时保留近期楼数',compressThreshold:'自动压缩节点阈值',detail:'摘要长度',userAction:'用户行动来源',cleanTags:'需要清洗的标签',excludeTags:'自动排除的标签',prompt:'摘要提示词',extractionPrompt:'状态提取提示词',compressionPrompt:'压缩提示词'};
  const memoryConfig = runtime.settings.snapshot().memory;
  for (const [key,value] of Object.entries(memoryConfig).filter(([key]) => key !== 'extract')) {
    let input; if (typeof value === 'boolean') input = checkField(optionsCard,memoryLabels[key],value); else if (typeof value === 'number') input = inputField(optionsCard,memoryLabels[key],value,'number'); else if (key === 'detail') input = selectField(optionsCard,memoryLabels[key],['brief','detailed'],value); else if (key === 'userAction') input = selectField(optionsCard,memoryLabels[key],[['intent','意图：由后续角色回复结算'],['settled','已发生：用户楼层也提取状态']],value); else input = inputField(optionsCard,memoryLabels[key],Array.isArray(value) ? value.join(',') : value,key.endsWith('Prompt') || key === 'prompt' ? 'textarea' : 'text'); memoryInputs[key] = input;
  }
  const extractInputs = {}; for (const [key,value] of Object.entries(memoryConfig.extract)) extractInputs[key] = checkField(optionsCard,`提取 ${KIND_LABELS[key]}`,value);
  action(optionsCard,'保存记忆选项',() => { const value = {...runtime.settings.snapshot().memory}; for (const [key,input] of Object.entries(memoryInputs)) value[key] = typeof memoryConfig[key] === 'boolean' ? input.checked : typeof memoryConfig[key] === 'number' ? Number(input.value) : Array.isArray(memoryConfig[key]) ? input.value.split(',').map(x => x.trim()).filter(Boolean) : input.value; value.extract = Object.fromEntries(Object.entries(extractInputs).map(([key,input]) => [key,input.checked])); return runtime.settings.update({memory:value}); });
  const uiCard = section(pages.settings,'界面与入口','入口独立开关；轻量模式保留基础编辑，完整模式显示全部工具。'); const mode = selectField(uiCard,'界面模式',['light','advanced','full'],runtime.settings.snapshot().ui.mode); const entries = {}; for (const [key,value] of Object.entries(runtime.settings.snapshot().ui.entries)) entries[key] = checkField(uiCard,`入口 ${key}`,value);
  action(uiCard,'保存界面入口',() => runtime.settings.update({ui:{mode:mode.value,entries:Object.fromEntries(Object.entries(entries).map(([key,input]) => [key,input.checked]))}}));
  const templateCard = section(pages.settings,'历法、提示模板与预设','模板支持 {{memory}}、{{storyTime}}、{{location}} 和 {{language}}。宏只读取已提交状态。'); const calendar = inputField(templateCard,'自定义历法 JSON',JSON.stringify(runtime.settings.snapshot().story.calendar,null,2),'textarea'); const completeTime = checkField(templateCard,'发送前附上当前故事时间',runtime.settings.snapshot().story.completeTimeBeforeSend); const language = inputField(templateCard,'模型输出语言',runtime.settings.snapshot().prompt.language); const template = inputField(templateCard,'统一注入模板',runtime.settings.snapshot().prompt.template,'textarea'); const recentWindow = inputField(templateCard,'注入时排除近期正文楼数',runtime.settings.snapshot().prompt.recentWindow,'number');
  action(templateCard,'保存历法与模板',() => { const config = runtime.settings.snapshot(); return runtime.settings.update({story:{calendar:JSON.parse(calendar.value),completeTimeBeforeSend:completeTime.checked},prompt:{...config.prompt,language:language.value,template:template.value,recentWindow:Number(recentWindow.value)}}); });
  action(templateCard,'恢复默认提示词',async () => { const defaults = p1Defaults(); const config = runtime.settings.snapshot(); await runtime.settings.update({memory:{...config.memory,prompt:defaults.memory.prompt,extractionPrompt:defaults.memory.extractionPrompt,compressionPrompt:defaults.memory.compressionPrompt},prompt:{...config.prompt,template:defaults.prompt.template}}); for (const key of ['prompt','extractionPrompt','compressionPrompt']) memoryInputs[key].value = defaults.memory[key]; template.value = defaults.prompt.template; });
  function loadConfiguration() { const config = runtime.settings.snapshot(); for (const [key,input] of Object.entries(memoryInputs)) { const value = config.memory[key]; if (typeof value === 'boolean') input.checked = value; else input.value = Array.isArray(value) ? value.join(',') : value; } for (const [key,input] of Object.entries(extractInputs)) input.checked = config.memory.extract[key]; for (const [key,input] of Object.entries(promptSectionInputs)) input.checked = config.prompt.sections[key]; for (const [key,input] of Object.entries(entries)) input.checked = config.ui.entries[key]; actors.value = config.prompt.actorIds.join(','); worldEnabled.checked = config.worldbook.enabled; bound.checked = config.worldbook.bound; booksInput.value = config.worldbook.books.join(','); scanDepth.value = config.worldbook.scanDepth; fallback.checked = config.api.fallbackToMain; mode.value = config.ui.mode; calendar.value = JSON.stringify(config.story.calendar,null,2); completeTime.checked = config.story.completeTimeBeforeSend; language.value = config.prompt.language; template.value = config.prompt.template; recentWindow.value = config.prompt.recentWindow; }
  action(templateCard,'导出可共享预设',() => download('memory-p1-preset.json',runtime.settings.snapshot())); const presetInput = inputField(templateCard,'导入预设 JSON','', 'textarea'); action(templateCard,'导入预设',async () => {await runtime.settings.update(JSON.parse(presetInput.value)); loadConfiguration(); if (runtime.getSnapshot().active) await runtime.p1.readMaterials();});
  const diagnosticsCard = section(pages.settings,'覆盖与状态诊断','来源失效、陈旧压缩、未覆盖楼层、任务和宿主能力分别显示。'); const diagnostics = el('pre',undefined,'memory-core-log-output'); diagnosticsCard.append(diagnostics);

  let lastSignature = ''; let routeSignature = ''; let worldSignature = '';
  function render(force = false) {
    const snapshot = runtime.getSnapshot(); const config = runtime.settings.snapshot(); const service = runtime.p1.snapshot(); const entities = Object.values(snapshot.state.entities);
    guide.textContent = !snapshot.active ? '请先打开一个聊天。' : !config.modules.memory ? '故事记忆未启用：可手工维护档案；开启后才能进行模型分析。' : `当前档案版本 ${snapshot.revision}；摘要 ${snapshot.coverage.summary?.summarized ?? 0}/${snapshot.coverage.summary?.eligible ?? 0}；角色范围 ${runtime.p1.actorIds().join(',') || '未识别，只发送公开信息'}。`;
    progress.textContent = `${{idle:'尚未开始',running:'分析中','awaiting-review':'待审阅',completed:'已完成',stopped:'已停止',failed:'失败'}[service.progress.status] ?? service.progress.status} · ${service.progress.completed}/${service.progress.total}${service.progress.error ? ` · ${service.progress.error}` : ''}`;
    quickMode.value = config.ui.mode; submittedOutput.textContent = service.lastBundle ? JSON.stringify({revision:service.lastBundle.revision,delivery:service.lastBundle.delivery,sourceIds:service.lastBundle.sourceIds,tokenCountKind:service.lastBundle.tokenCountKind,text:service.lastBundle.text},null,2) : '尚未向宿主提交正文生成材料。';
    const preview = snapshot.active ? runtime.p1.previewPrompt() : null; promptInfo.textContent = preview ? `版本 ${preview.revision ?? '未同步'} · ${preview.tokenCount} token（估计） · 来源 ${preview.sourceIds.length} 项 · 最近交付 ${service.lastBundle?.delivery ?? '尚未提交'}` : '请打开聊天'; promptOutput.textContent = preview?.text || '当前没有可发送材料。'; capabilities.textContent = JSON.stringify(runtime.capabilities().host,null,2); diagnostics.textContent = JSON.stringify(runtime.p1.diagnostics(),null,2);
    const nextRoutes = canonical([config.channels,config.routing]); if (routeSignature !== nextRoutes) { routeSignature = nextRoutes; const options = [{id:'main',name:'酒馆主 API'},...config.channels]; for (const [task,input] of Object.entries(routes)) { input.replaceChildren(); for (const option of options) { const o = el('option',option.name); o.value = option.id; input.append(o); } input.value = config.routing[task] ?? config.routing.default; } const previous = channelSelect.value; channelSelect.replaceChildren(); for (const channel of config.channels) { const o = el('option',channel.name); o.value = channel.id; channelSelect.append(o); } channelSelect.value = config.channels.some(c => c.id === previous) ? previous : config.channels[0]?.id ?? ''; loadChannel(); }
    const nextWorld = canonical(service.materials); if (worldSignature !== nextWorld) { worldSignature = nextWorld; worldList.replaceChildren(); worldList.append(el('p',`可用世界书：${service.materials.books.join('、') || '无名称接口'}；${service.materials.scanMode}`)); for (const warning of service.materials.warnings) worldList.append(el('p',warning,'memory-core-feedback')); for (const entry of service.materials.entries) { const row = el('div',undefined,'memory-core-summary-row'); row.append(el('strong',`${entry.book} · ${entry.name} [${entry.id}]`),el('p',entry.reason),el('pre',entry.text,'memory-core-log-output')); const selected = checkField(row,'选入此条目',config.worldbook.selectedEntries.includes(entry.id)); const excluded = checkField(row,'排除此条目',config.worldbook.excludedEntries.includes(entry.id)); const saveSelection = async () => { const current = runtime.settings.snapshot(); const updateList = (list,checked) => [...new Set([...list.filter(id => id !== entry.id),...(checked ? [entry.id] : [])])]; await runtime.settings.update({worldbook:{...current.worldbook,selectedEntries:updateList(current.worldbook.selectedEntries,selected.checked),excludedEntries:updateList(current.worldbook.excludedEntries,excluded.checked)}}); await runtime.p1.readMaterials(); }; selected.addEventListener('change',() => void saveSelection().catch(error => feedback(error.message,true))); excluded.addEventListener('change',() => void saveSelection().catch(error => feedback(error.message,true))); worldList.append(row); } for (const material of service.materials.materials.filter(m => m.origin !== 'worldbook-setting')) { const row = el('div',undefined,'memory-core-summary-row'); row.append(el('strong',material.origin),el('pre',material.text,'memory-core-log-output')); worldList.append(row); } }
    const next = canonical([snapshot.storeId ?? null,snapshot.revision ?? null,kindFilter.value,search.value,levelFilter.value,rawMode.checked,config.ui.mode]); if (!force && next === lastSignature) return; lastSignature = next;
    const focusedDraft = document.activeElement?.dataset.draftId; const selection = focusedDraft ? [document.activeElement.selectionStart,document.activeElement.selectionEnd] : null;
    draftsList.replaceChildren(); for (const draft of entities.filter(e => e.kind === 'draft' && e.fields.status === 'pending')) { const row = el('div',undefined,'memory-core-summary-row'); row.append(el('strong',`${draft.fields.type === 'analysis' ? '楼层分析' : '合并压缩'} · ${draft.fields.sourceKey || draft.id}`)); const text = inputField(row,'待提交摘要',draftEdits.get(draft.id) ?? draft.fields.text,'textarea'); text.dataset.draftId = draft.id; text.addEventListener('input',() => draftEdits.set(draft.id,text.value)); const details = el('details'); details.append(el('summary','变更明细'),el('pre',JSON.stringify(draft.fields.ops,null,2),'memory-core-log-output')); row.append(details); action(row,'保存审阅修订',async () => { await runtime.p1.reviseDraft(draft.id,text.value); draftEdits.delete(draft.id); }); action(row,'确认提交',async () => { if (text.value !== draft.fields.text) await runtime.p1.reviseDraft(draft.id,text.value); await runtime.p1.accept([draft.id]); draftEdits.delete(draft.id); }); action(row,'拒绝结果',() => runtime.p1.reject(draft.id)); draftsList.append(row); if (focusedDraft === draft.id) {text.focus({preventScroll:true}); text.setSelectionRange(...selection);} } if (!draftsList.children.length) draftsList.append(el('p','没有待审阅结果。'));
    nodeList.replaceChildren(); for (const node of summaryGraph({...snapshot,messages:snapshot.messages ?? []})) { const row = el('div',undefined,'memory-core-summary-row'); const selected = checkField(row,`${node.name} · 层级 ${node.fields.level ?? 0} · ${node.coverage.length} 楼 · ${node.valid ? '有效' : node.reason}`,nodeSelections.has(node.id)); selected.addEventListener('change',() => selected.checked ? nodeSelections.add(node.id) : nodeSelections.delete(node.id)); row.append(el('p',node.fields.text)); if (rawMode.checked) { const sources = runtime.sourceData().chat; row.append(el('pre',node.coverage.map(ref => { const source = snapshot.messages.find(m => m.id === ref.messageId); return source ? `第 ${source.index + 1} 楼：${sources[source.index]?.mes ?? ''}` : '来源已删除'; }).join('\n'),'memory-core-log-output')); } const visibility = selectField(row,'摘要可见范围',['narrator','public','private'],node.fields.visibility ?? 'narrator'); const audience = inputField(row,'知情角色 ID',(node.fields.audienceIds ?? []).join(',')); action(row,'保存摘要可见范围',() => runtime.p1.manual([{type:'set',entityId:node.id,path:['visibility'],value:visibility.value},{type:'set',entityId:node.id,path:['audienceIds'],value:audience.value.split(',').map(x => x.trim()).filter(Boolean)}],'编辑摘要可见范围')); if (node.fields.childIds?.length) action(row,node.fields.disabled ? '恢复压缩节点' : '撤销使用这个压缩',() => runtime.p1.manual([{type:'set',entityId:node.id,path:['disabled'],value:!node.fields.disabled}],'切换压缩节点')); nodeList.append(row); }
    const view = snapshot.active ? domainView(snapshot) : {characters:[],scenes:[]}; stateList.replaceChildren();
    for (const entity of entities.filter(e => Object.hasOwn(DOMAIN_DEFAULTS,e.kind)).filter(e => !kindFilter.value || e.kind === kindFilter.value).filter(e => [e.name,...e.aliases,e.fields.actorId ?? ''].join(' ').includes(search.value)).filter(e => levelFilter.value === '全部' || e.fields.rank === levelFilter.value || e.fields.importance === levelFilter.value || view.characters.find(c => c.id === e.id)?.presence === levelFilter.value || levelFilter.value === '星标' && e.fields.starred || levelFilter.value === '置顶' && e.fields.pinned)) {
      const row = el('div',undefined,'memory-core-summary-row'); const selectBox = checkField(row,`${KIND_LABELS[entity.kind]} · ${entity.name} [${entity.id}]`,selectedEntities.has(entity.id)); selectBox.addEventListener('change',() => selectBox.checked ? selectedEntities.add(entity.id) : selectedEntities.delete(entity.id)); const derived = view.characters.find(c => c.id === entity.id); row.append(el('p',derived ? `在场 ${valueLabels[derived.presence]} · 年龄 ${derived.age ?? '未知'}` : `${valueLabels[entity.fields.importance] ?? ''} ${valueLabels[entity.fields.status] ?? ''}`)); const values = el('dl',undefined,'memory-core-state-values'); for (const [key,value] of Object.entries(entity.fields).filter(([key]) => key !== 'sourceMessageIds')) {values.append(el('dt',labels[key] ?? key),el('dd',value == null ? '未知' : typeof value === 'string' ? valueLabels[value] ?? value : typeof value === 'boolean' ? value ? '是' : '否' : JSON.stringify(value)));} row.append(values); action(row,'编辑',() => { loadEditor(entity); editorCard.scrollIntoView({block:'start'}); }); const detail = el('details'); detail.hidden = config.ui.mode !== 'full'; detail.append(el('summary','字段来源与变动记录')); const history = runtime.getHistory({after:0,limit:1000}).filter(event => event.ops?.some(op => op.entityId === entity.id)); detail.append(el('pre',JSON.stringify(history.map(event => ({revision:event.revision,origin:event.origin,evidence:event.evidence,createdAt:event.createdAt,ops:event.ops.filter(op => op.entityId === entity.id)})),null,2),'memory-core-log-output')); row.append(detail); let press; row.addEventListener('pointerdown',event => { if (event.target.closest('button,input,select,textarea,summary')) return; press = setTimeout(() => { selectBox.checked = true; selectedEntities.add(entity.id); },500); }); for (const name of ['pointerup','pointercancel','pointermove']) row.addEventListener(name,() => clearTimeout(press)); stateList.append(row);
    }
    mapList.replaceChildren(); const appendScene = (parent,depth,seen) => { for (const scene of view.scenes.filter(e => e.fields.parentId === parent)) { if (seen.has(scene.id)) continue; const label = el('p',`${'　'.repeat(depth)}${scene.name} [${scene.id}]`); label.style.paddingInlineStart = `${depth * 12}px`; mapList.append(label); appendScene(scene.id,depth + 1,new Set([...seen,scene.id])); } }; appendScene(null,0,new Set());
    undoList.replaceChildren(); for (const undo of entities.filter(e => e.kind === 'undo' && !e.fields.used).slice(-10).reverse()) action(undoList,`撤销 ${undo.name}`,() => runtime.p1.undo(undo.id));
    const light = config.ui.mode === 'light'; diagnosticsCard.hidden = config.ui.mode !== 'full'; capabilities.hidden = config.ui.mode !== 'full'; for (const key of ['world','api','migration','settings']) pages[key].dataset.advanced = 'true'; for (const button of nav.children) if (['世界书','任务渠道','旧总结导入','选项与提示词'].includes(button.textContent)) button.hidden = light; if (light && ['world','api','migration','settings'].includes(activePage)) select('memory');
  }
  const floorListener = event => { start.value = event.detail.floor; end.value = event.detail.floor; select('memory'); rangeCard.scrollIntoView({block:'start'}); }; container.addEventListener('memory-core:floor',floorListener);
  return { render, dispose: () => container.removeEventListener('memory-core:floor',floorListener) };
}
